config/routes.rb
Tands::Application.routes.draw do

  root :to => 'welcome#index'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/new.html.erb
<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title
    T &amp; S Mobile Hearing -
    = content_for?(:title) ? yield(:title) : "T &amp; S Mobile Hearing"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag
  = javascript_include_tag "application"

%body
  .wrapper.header
    .row
      .branding
        = link_to (image_tag "logo.png"), "", class: "logo"
  = yield
  .wrapper.footer
    .row
      = render :partial => "shared/footer"

app/views/shared/_banner.html.haml
.slider-wrapper.theme-default
  #slider.nivoSlider
    = image_tag "TIM-Title-slide.png"
    = image_tag "truck-title-headshot-slide.png"

:javascript
  $(window).load(function() {
    $('#slider').nivoSlider({
      effect: 'fade',
      pauseTime: 15000,
      animSpeed: 0
    });
  });

app/views/shared/_footer.html.haml
.row
  .large-4.columns
    %h3.border-bottom Contact Us
    %p T&S Mobile Hearing Express
    %address 
      %p 
        1279 Patriot St
        %br Billings, MT 59715
      %ul 
        %li T: 406.672.6696
        %li F: 406.259.0336
        %li C: 406.670.6696
  .large-4.columns
    %h3.border-bottom Contact Form
    = form_for @message, :url => contact_path do |form|
      %fieldset.fields
        .field
          = form.label :name
          = form.text_field :name
        .field
          = form.label :email
          = form.text_field :email
        .field
          = form.label :subject
          = form.text_field :subject
        .field
          = form.label :body
          = form.text_area :body
      %fieldset.actions
        = form.submit "Send", class: "submit"
  .large-4.columns
    %h3.border-bottom Service Area
    = image_tag "service-area-map.png"
.row
  %p.small 
    Copyright &copy; 2005 -
    = Time.now.year
    T&amp;S Mobile Hearing Express. All Rights Reserved.

app/views/welcome/index.html.haml
- content_for(:title, 'Welcome')
.wrapper.banner
  .row
    = render :partial => "shared/banner"
.wrapper.section
  .row
    .large-12
      %h3 T&amp;S Mobile Hearing Express offers on-site audiometric (hearing) tests to assist your company in complying with the requirements of Hearing Conservation programs as required in CFR 29 1910.95 and CFR 30 section 62.
    .row
      .large-4.columns
        %p 
          Our services present a cost savings to your company between 30 to 50% by administering on-site testing as opposed to sending employees to an off-site facility. Reduction in "lost time" and liability for travel, combined with the ability to conduct four tests simultaneously &ndash; a rate of twelve employees per hour, makes on-site hearing tests an enormously economical, safe, and wise choice for your company.
      .large-4.columns 
        = image_tag "Tim-Full-Body.png", :class => "alignleft" 
        %p
          Tim Doerr, President and Owner of T&amp;S Mobile Hearing Express, has been a certified Hearing Conservationist since 1971 and has operated a mobile hearing unit for the past eleven years. Mr. Doerr also has 24 years of experience in the U.S. Air Force in the field of Occupational / Industrial Medicine.
      .large-4.columns 
        %p
          Dr. Gene Bukowski is our Professional Reviewer. He has 29 years of experience In Industrial/Occupational hearing. Additionally, Dr. Bukowski is a certified Hearing Conservation Instructor and Credentials Hearing Conservationist in the state of Montana. All hearing tests and medical histories are reviewed per OSHA/MSHA mandates. Dr. Bukowski will make recommendations if follow-up evaluations are required.
    .row
      .large-4.columns 
        = image_tag "earscan-estram_300-150x150.jpg", :class => "alignleft article-image" 
        %p
          Our mobile unit is equipped with state-of-the-art testing machines. Ambient noise levels in the unit are monitored continuously with a bio-acoustic simulator. The simulator insures compliance with OSHA/MSHA referencing noise levels inside mobile testing units. All equipment meets or exceeds those requirements and specifications of OSHA/MSHA regarding Hearing Conservation programs.
      .large-4.columns 
        = image_tag "testing-booths-150x150.png", :class => "alignleft article-image" 
        %p
          Prior to testing, employees will be required to fill out a brief medical history pertaining to their hearing. This information is loaded into the database for Hearing Conservation and is used if a change or loss of hearing has been identified.
      .large-4.columns 
        = image_tag "Documents.png", :class => "alignleft article-image" 
        %p
          Employees are instructed as to the purposes and procedures of audiometric testing. A copy of their results will be provided immediately after testing. Hearing Conservation Training is provided to you and your employees at no additional charge.
    .row.border-bottom
      .large-12.columns
        %h4 TOPICS OF EDUCATION:
    .row
      .large-4.columns
        %ol
          %li Current test results.
          %li Effects of loud noise on an individual's hearing.
          %li Hearing protection devices available to employees; their advantages and disadvantages; technique for proper selection, fit, use, and care.
      .large-4.columns
        %p
          A complete report will be provided to your company inclusive of the data necessary to evaluate your company's Hearing Conservation program.
        %p
          Your company’s safety representative will be given a verbal briefing prior to our departure informing them of any problems and/or issues.
      .large-4.columns
        %ol
          %lh T&amp;S Mobile Hearing Express will also provide an easy to read overview of your company's Hearing Conservation program with your final report which outlines:
          %li Overall Findings
          %li Conclusions
          %li Recommendations